
mybatis:
  type-aliases-package: com.jjbx.dao.dto
  mapper-locations: classpath*:mappers/*.xml

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 全局熔断超时时长
            timeoutInMilliseconds: 10000

fosun:
  encryptKey:
    #投保报文md5秘钥
    md5: ewealth
    #投保报文aes秘钥
    aes: FOSUN2016
  health:
    url:
      getRequestURL-url: http://pre-weixin.fosun-uhi.com/ebiz-entry/ebiz/getRequestURL.do?action=dealBiz
      intelligentSecurity-url: http://pre-weixin.fosun-uhi.com/ebiz-entry/ebiz/intelligentSecurity.do?action=dealBiz
      queryHealthNotificationInfo-url: http://pre-weixin.fosun-uhi.com/ebiz-entry/ebiz/queryHealthNotificationInfo.do?action=dealBiz
  order:
    url:
      personalInsuredOrder-url: http://pre-weixin.fosun-uhi.com/ebiz-entry/ebiz/applyNewCont.do?action=dealBiz
      familyInsuredOrder-url: http://pre-weixin.fosun-uhi.com/ebiz-entry/ebiz/familyApplyNewCont.do?action=dealBiz
      acceptInsuredOrder-url: http://pre-weixin.fosun-uhi.com/ebiz-entry/ebiz/confirmCont.do?action=dealBiz
  query:
    url:
      pesonalInsuredOrderQuery-url: http://pre-weixin.fosun-uhi.com/ebiz-entry/ebiz/queryCustomerPolicy.do?action=dealBiz
      familyInsuredOrderQuery-url: http://pre-weixin.fosun-uhi.com/ebiz-entry/ebiz/queryFamilyPolicyDetail.do?action=dealBiz
      insuredOrderStatusQuery-url: http://pre-weixin.fosun-uhi.com/ebiz-entry/ebiz/queryContInfoByPrtNo.do?action=dealBiz
  cancle:
    url:
      personalInsuredCancle-url: http://pre-weixin.fosun-uhi.com/ebiz-entry/ebiz/contCancle.do?action=dealBiz
  download:
    url:
      personalDownload-url: http://pre-weixin.fosun-uhi.com/ebiz-entry/ebiz/download.do?action=dealBiz